/* 
postgresql database initialize script
*/

/* ---------- drop all tables if exist ---------- */
DROP TABLE IF EXISTS PLAYER, TEAM, STATE, COLOR;

/* ---------- create tables ---------- */
CREATE TABLE COLOR(
  COLOR_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE STATE(
  STATE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE TEAM(
  TEAM_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  STATE_ID INT NOT NULL, -- foreign key: state
  COLOR_ID INT NOT NULL, -- foreign key: color
  WINS INT NOT NULL,
  LOSSES INT NOT NULL,

  CONSTRAINT FK_STATE 
    FOREIGN KEY(STATE_ID) 
    REFERENCES STATE(STATE_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT FK_COLOR 
    FOREIGN KEY(COLOR_ID) 
    REFERENCES COLOR(COLOR_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE PLAYER(
  PLAYER_ID SERIAL PRIMARY KEY,
  TEAM_ID INT NOT NULL, -- foreign key: team
  UNIFORM_NUM INT NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  MPG INT NOT NULL,
  PPG INT NOT NULL,
  RPG INT NOT NULL,
  APG INT NOT NULL,
  SPG FLOAT NOT NULL,
  BPG FLOAT NOT NULL,

  CONSTRAINT FK_TEAM 
    FOREIGN KEY(TEAM_ID) 
    REFERENCES TEAM(TEAM_ID) 
    ON UPDATE CASCADE 
    ON DELETE SET NULL
);